apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}-service
  namespace: {{ include "demo-app.namespace" . | default "demo-app" }}
spec:
  selector:
    app: {{ include "demo-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ include "demo-app.containerPort" . | default 5000 }}
      targetPort: {{ include "demo-app.containerPort" . | default 5000 }}
      nodePort: {{ include "demo-app.service.nodePort" . | default 30088 }}
  type: NodePort
