namespace: demo-app
replicas: 1

image:
  repository: ${{ secrets.DOCKERHUB_USERNAME }}/devsecops_project_1
  tag: latest

containerPort: 5000

hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

service:
  nodePort: 30088

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 600m