---
# Source: demo-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-demo-app-service
  namespace: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30088
  type: NodePort
