name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  id-token: write
  contents: write
  security-events: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: 'omarfrikha96/DevSecOps-project'
          path: ./repo

      - name: Generate Kubernetes Manifests with Helm
        env:
          NAMESPACE: demo-app
          IMAGE_REPO: "${{ secrets.DOCKERHUB_USERNAME }}/"
          IMAGE_NAME: devsecops_project
        run: |
          cd repo/k8s-manifest/demo-app
          helm template release . --debug --set namespace=${NAMESPACE} --set image.repository=${IMAGE_REPO}${IMAGE_NAME} --set image.tag=${{ github.sha }} --output-dir ./..
          
      - name: Update ArgoCD Manifests
        run: |
          cd repo/k8s-manifest/argocd
          cd ..
          mkdir -p argocd/manifests/apps/demo-app
          rm -rf argocd/manifests/apps/demo-app/*
          mv ./demo-app/templates/* argocd/manifests/apps/demo-app/
          git config --global user.email "no-reply@no-reply.io"
          git config --global user.name "CI_CD Bot"
          cd argocd
          git add .
          git commit -m "Update demo-app commit ${{ github.sha }} "
          git remote set-url origin https://github.com/omarfrikha96/DevSecOps-project.git
          git push origin main